Compatible with old cmake
ethz-adrl/control-toolbox pull request #136
Opened 2020-05-22 09:27 UTC by romainreignier

Fix https://github.com/ethz-adrl/control-toolbox/pull/116#issuecomment-625800528 after discussion in https://github.com/ethz-adrl/control-toolbox/pull/129

I have tested it on Xenial and Bionic but because ROS is not yet released on Focal, I did not test the case when Cmake > 3.12. @acxz could you try it please?

I have also fixed the crash on the `hist` test of `plotTest`.

2020-05-22 12:45 UTC, markusgft approved these changes
Looks very good to me, although I am not able to test this in my current PC setup. 
@acxz can you confirm that it covers your usecase, too?
If everyone is happy, please feel free to trigger the merge.

2020-05-22 21:30 UTC, acxz commented
I'm sorry to report that it does not work on my system. Let me dig a bit deeper.

2020-05-22 21:41 UTC, acxz requested changes

2020-05-22 21:41 UTC, acxz commented on ct_core/CMakeLists.txt
> +    find_package(Python COMPONENTS Development Numpy QUIET)
```suggestion
    find_package(Python COMPONENTS Development NumPy QUIET)
```

Just a small typo

2020-05-22 21:43 UTC, acxz commented on ct_core/CMakeLists.txt
> +    find_package(Python COMPONENTS Development Numpy QUIET)
PR is ready with this fix

2020-05-23 07:47 UTC, romainreignier commented
Ah sorry, my mistake. I will fix it tomorrow.

22 mai 2020 23:30:42 acxz <notifications@github.com>:
> I'm sorry to report that it does not work on my system. Let me dig a bit deeper. —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[https://github.com/ethz-adrl/control-toolbox/pull/136#issuecomment-632915908], or unsubscribe[https://github.com/notifications/unsubscribe-auth/ACDPSYAIWPRIJEWPFGENHW3RS3VIDANCNFSM4NHUGBWA]. [https://github.com/notifications/beacon/ACDPSYAG7OZZMHNCHUJ5IPDRS3VIDA5CNFSM4NHUGBWKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEW4YPRA.gif]

2020-05-24 09:22 UTC, merged

2020-05-25 08:00 UTC, romainreignier commented
Thank you @markusgft for fixing the typo.
I was away from home this week-end.

Anyway, I have managed to test it on Ubuntu Focal and ROS [Noetic testing](https://discourse.ros.org/t/ros-noetic-call-for-testing/14203).
It works, the histogram is displayed in `plotTest` but a seg fault happen on the next test while it was working on Ubuntu 18.04 and 16.04.
@acxz Does the `plotTest` seg fault on your side? After the histogram?

2020-05-25 08:24 UTC, romainreignier commented
From a quick `gdb` session, the segfault seems to be in the histogram `show()` call, even if it is already shown on the screen.
But that is another issue, not related at all with CMake version.

2020-05-25 11:12 UTC, acxz commented
Yep can reproduce, I have a pretty big hunch that if we incorporate upstream changes from (`matplotlib-cpp`)[https://github.com/lava/matplotlib-cpp] specifically this commit: https://github.com/lava/matplotlib-cpp/commit/60dcd64c8fd4766e5426f57decfb765422a1d3fe it'll fix it.

This is the particular line that prob needs to be changed: https://github.com/lava/matplotlib-cpp/commit/60dcd64c8fd4766e5426f57decfb765422a1d3fe#diff-59dbbec4311029188f570e995bb6a594R714 in our local copy of the plotting script.

2020-05-25 12:40 UTC, romainreignier commented
Interesting, but I have try to add a couple of them and it does not fix anything: https://github.com/romainreignier/control-toolbox/commit/f2349698ba9c4295a266a3fe08c1f6e4ed69de47